[project]
name = "analyze"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "pandas>=2.3.2",
]

[dependency-groups]
dev = [
    "pandas-stubs>=2.3.2.250827",
]
